// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getXIC
NumericMatrix getXIC(List scans, double mzmin, double mzmax);
RcppExport SEXP MSsary_getXIC(SEXP scansSEXP, SEXP mzminSEXP, SEXP mzmaxSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< List >::type scans(scansSEXP );
        Rcpp::traits::input_parameter< double >::type mzmin(mzminSEXP );
        Rcpp::traits::input_parameter< double >::type mzmax(mzmaxSEXP );
        NumericMatrix __result = getXIC(scans, mzmin, mzmax);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
