# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mqCpp <- function(scans, scantime, minIntensity, minCentroids, consecMissedLim, ppm, criticalVal, segs, scanBack) {
    .Call('MSsary_mqCpp', PACKAGE = 'MSsary', scans, scantime, minIntensity, minCentroids, consecMissedLim, ppm, criticalVal, segs, scanBack)
}

#' XIC from a list of scans
#' 
#' This function extracts total and base ions from each scan in a list based on
#' a min and max m/z value given
#' 
#' @param scans A list of matrices with scan data as returned by the msData 
#' method for MsScanList
#' 
#' @param mzmin A numeric giving the minimum mz value to include
#' 
#' @param mzmax A numeric giving the maximum mz value to include
#' 
#' @return A matrix with a length equal to the length of scans, and with two 
#' columns. The first column hold the summed intensities, the second the 
#' maximum intensity for each scan
#' 
#' @noRd
#' 
getXIC <- function(scans, mzmin, mzmax) {
    .Call('MSsary_getXIC', PACKAGE = 'MSsary', scans, mzmin, mzmax)
}

#' Get intensity threshold for a given signal-to-noise ratio
#' 
#' This function takes a scan and finds the first non-noise ion in it based on
#' the dynamic noise level algorithm described by Xu and Freitas (2009). It 
#' returns the intensity of that ion.
#' 
#' @param scan A matrix with mz and intensity values
#' @param sn The required minimum signal-to-noise to be considered a real 
#' signal
#' @param rho The modifier to use for the second lowest ion special case
#' 
#' @return A numeric with the intensity of the first ion that gets accepted as
#' a true signal
#' 
#' @references Xu, H., & Freitas, M. A. (2009). A dynamic noise level algorithm 
#' for spectral screening of peptide MS/MS spectra. BMC Bioinformatics, 11, 
#' 436–436. doi:10.1186/1471-2105-11-436
#' 
scanNoise <- function(scan, sn, rho) {
    .Call('MSsary_scanNoise', PACKAGE = 'MSsary', scan, sn, rho)
}

