# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mqCpp <- function(scans, scantime, minIntensity, minCentroids, consecMissedLim, ppm, criticalVal, segs, scanBack) {
    .Call('MSsary_mqCpp', PACKAGE = 'MSsary', scans, scantime, minIntensity, minCentroids, consecMissedLim, ppm, criticalVal, segs, scanBack)
}

#' XIC from a list of scans
#' 
#' This function extracts total and base ions from each scan in a list based on
#' a min and max m/z value given
#' 
#' @param scans A list of matrices with scan data as returned by the msData 
#' method for MsScanList
#' 
#' @param mzmin A numeric giving the minimum mz value to include
#' 
#' @param mzmax A numeric giving the maximum mz value to include
#' 
#' @return A matrix with a length equal to the length of scans, and with two 
#' columns. The first column hold the summed intensities, the second the 
#' maximum intensity for each scan
#' 
#' @noRd
#' 
getXIC <- function(scans, mzmin, mzmax) {
    .Call('MSsary_getXIC', PACKAGE = 'MSsary', scans, mzmin, mzmax)
}

